#生产环境
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: XXX
#    password: XXX
#    url: jdbc:mysql://111.231.14.181:3306/smart_home?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
#    #监控 --http://localhost:8080/andy/druid
#    #filters: stat,wall
#    #schema: classpath:/org/springframework/batch/core/schema-mysql.sql
#    druid:
#      #aop-patterns: com.andy.sboot.*
#      filter:
#        wall:
#          enabled: true
#          config:
#            update-allow: true
#
#        stat:
#          log-slow-sql: true
#          slow-sql-millis: 1000
#          enabled: true
#  servlet:
#    multipart:
#      max-file-size:  10MB
#      max-request-size: 30MB
#
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.andy.home.po
#
##pagehelper分页插件配置
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
#
#
#windows:
#  file:
#    path:  e:/fileUpload/file
#
#linux:
#  file:
#    path:  /application/file
#
#protocol:  https://
#ip:  111.231.14.181
#domain:  xuyuefei.com
#defaultImageSrc:  /file/default.PNG
#FILE_PATH_DIR:  file

#测试环境
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: XXX
    password: XXX
    url: jdbc:mysql://111.231.14.181:3306/smart_home(test)?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    #监控 --http://localhost:8080/andy/druid
    #filters: stat,wall
    #schema: classpath:/org/springframework/batch/core/schema-mysql.sql
    druid:
      #aop-patterns: com.andy.sboot.*
      filter:
        wall:
          enabled: true
          config:
            update-allow: true

        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          enabled: true
  servlet:
    multipart:
      max-file-size:  10MB
      max-request-size: 30MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.andy.home.po

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


windows:
  file:
    path:  e:/fileUpload/file

linux:
  file:
    path:  /application/file_test

protocol:  https://
ip:  111.231.14.181
domain:  test.xuyuefei.com
defaultImageSrc:  /file_test/default.PNG

FILE_PATH_DIR:  file_test

